CREATE TABLE USERS (
	ID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(32) NOT NULL UNIQUE,
	PASSWORD VARCHAR(255) NOT NULL,
	FIRST_NAME VARCHAR(16) NOT NULL,
	LAST_NAME VARCHAR(16) NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	ROLE VARCHAR(10) NOT NULL,
	IMAGE VARCHAR(255)
);

CREATE TABLE ADS (
	ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(32) NOT NULL,
	PRICE INTEGER NOT NULL CHECK (
		PRICE >= 0
		AND PRICE <= 10000000
	),
	DESCRIPTION VARCHAR(64) NOT NULL,
	IMAGE VARCHAR(255),
	AUTHOR_ID INTEGER NOT NULL REFERENCES USERS (ID)
);

CREATE TABLE COMMENTS (
	ID SERIAL PRIMARY KEY,
	TEXT VARCHAR(64) NOT NULL,
	CREATED_AT BIGINT NOT NULL,
	AUTHOR_ID INTEGER NOT NULL REFERENCES USERS (ID),
	AD_ID INTEGER NOT NULL REFERENCES ADS (ID)
);

CREATE INDEX IDX_ADS_AUTHOR_ID ON ADS (AUTHOR_ID);

CREATE INDEX IDX_COMMENTS_AD_ID ON COMMENTS (AD_ID);

CREATE INDEX IDX_COMMENTS_AUTHOR_ID ON COMMENTS (AUTHOR_ID);